### ISSUE TITLE
how does the front end contact to the back end?

### ISSUE THREAD

**Issue by Tetous** [animeandromeda/animeandromeda-react#1]

**Comment by shoegazeryu** [comment]
Hi tetous! The front-end contact the backend via API calls. You have to set 2 environment variables:

`REACT_APP_API_URL` to set the URL of the "backend".
For example in this one I'll set the URL of our public API: https://api.animeandromeda.net/api/v2/

The other variable, `REACT_APP_API_URL`, is not strictly needed, it's to contact the API that provides the authentication functionalities.
